name: Deploy CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
          FB_DB_URL: ${{ secrets.FB_DB_URL }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}